#pragma once

#include "SDL3/SDL.h"
#include "SDL3_image/SDL_image.h"
#include "SDL3_ttf/SDL_ttf.h"
#include "SDL3_mixer/SDL_mixer.h"

#include <iostream>
#include <vector>
#include <string>

#include "Tools/ServiceLocator.h"

class Debug;
class SceneManager;
class AppFacadeService;
class InputManager;

// The main application class that initializes SDL,
// creates the window and renderer, and runs the main game loop
class SDLApplication {
	friend AppFacadeService;
public:
	// initializes the game application, it will initialize SDL, create the window and renderer, and initialize the global services
	bool init();
	// begins the main game loop,
	// it will handle events, update the game state and render the game every frame until the application is closed
	void run();
 
private:
	// Initializes the global services of the application
	void initGlobalServices();
	// Handles the events generated by SDL and sends them to the SceneManager
	void handleEvents();
	// Updates the game state by calling the update method of the SceneManager
	void update(float deltaTime);
	// Renders the game by calling the render method of the SceneManager
	void render();

	// Closes the application by quitting SDL and cleaning up the resources
	void quit();
	// Returns a reference to the SDL_Renderer of the application,
	// it will be used by the scenes to render the game objects
	SDL_Renderer& getRenderer() { return *m_pRenderer; }

	// bool flag that indicates whether the application is running,
	// it will be set to true when the application is initialized and set to false when the application is closed
	bool m_bIsRunning = false;
	// The SDL window that represents the application window
	SDL_Window* m_pWindow;
	// The SDL renderer that represents the application renderer
	SDL_Renderer* m_pRenderer;
	// The SDL_mixer mixer that represents the application mixer,
	// it will be used to play music and sounds in the game
	MIX_Mixer* m_sfxMixer;
	MIX_Mixer* m_musicMixer;
	// The service locator that holds the global services of the application
	ServiceLocator m_ServiceLocator;
	// The input manager that manages the input of the application
	InputManager* m_inputManager;
	// Scene manager
	SceneManager* m_sceneManager;

	Debug* m_debug;

	// The target resolution and FPS of the application
	const int M_RESOLUTIONWIDTH = 1920;
	const int M_RESOLUTIONHEIGHT = 1080;
	const int M_IFPS = 60;

	// The frame delay in milliseconds,
	// calculated from the target FPS.
	const uint32_t m_iFrameDelay = 1000 / M_IFPS;
};